// <auto-generated />
using System;
using GlassesShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassesShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlassesShop.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Account_Role", "[Role] IN (N'Customer', N'Staff', N'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsLocked = false,
                            PasswordHash = "cIxkaRlf6+h8hvydSSwJW+VqHp2aXJrJ8Bz2hNZ0AVQ=",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            AccountID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsLocked = false,
                            PasswordHash = "TeAIjA2k0T3/YkinS8oU1/Aj+tsg7T1fD9GwRJ1AZFo=",
                            Role = "Staff",
                            Username = "staff01"
                        },
                        new
                        {
                            AccountID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsLocked = false,
                            PasswordHash = "SFBkCgS9TjspxIZa0JiKUgMgcX/nDdwbOrLltWb+uS8=",
                            Role = "Customer",
                            Username = "khachhang01"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            BrandName = "Ray-Ban",
                            Description = "Thương hiệu kính mắt Mỹ"
                        },
                        new
                        {
                            BrandID = 2,
                            BrandName = "Gucci",
                            Description = "Thương hiệu thời trang Ý"
                        },
                        new
                        {
                            BrandID = 3,
                            BrandName = "Oakley",
                            Description = "Kính thể thao cao cấp"
                        },
                        new
                        {
                            BrandID = 4,
                            BrandName = "Molsion",
                            Description = "Thương hiệu kính Trung Quốc"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.CartDetail", b =>
                {
                    b.Property<int>("CartDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartDetailID"));

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("CartDetailID");

                    b.HasIndex("VariantID");

                    b.HasIndex("CartID", "VariantID")
                        .IsUnique();

                    b.ToTable("CartDetails", t =>
                        {
                            t.HasCheckConstraint("CK_CartDetail_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Kính thời trang",
                            Description = "Kính mắt thời trang hoàn chỉnh"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumberPhone")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Gender", "[Gender] IN (N'Nam', N'Nữ')");
                        });

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            AccountID = 3,
                            Address = "123 Cầu Giấy, Hà Nội",
                            Email = "mai@gmail.com",
                            FullName = "Trần Thị Mai",
                            Gender = "Nữ",
                            NumberPhone = "0987654321"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("StaffID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Status", "[OrderStatus] IN (N'Chờ xác nhận', N'Đã xác nhận', N'Đang giao', N'Đã giao', N'Đã hủy')");
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("VariantID");

                    b.HasIndex("OrderID", "VariantID")
                        .IsUnique();

                    b.ToTable("OrderDetails", t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetail_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Status", "[PaymentStatus] IN (N'Chưa thanh toán', N'Đã thanh toán', N'Thất bại', N'Đã hoàn tiền')");
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            BrandID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kính phi công huyền thoại, gọng kim loại nhẹ, tròng chống UV400.",
                            IsActive = true,
                            Material = "Kim loại",
                            ProductName = "Kính Ray-Ban Aviator Classic",
                            Style = "Phi công"
                        },
                        new
                        {
                            ProductID = 2,
                            BrandID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thiết kế vuông cổ điển, phù hợp mọi khuôn mặt.",
                            IsActive = true,
                            Material = "Nhựa Acetate",
                            ProductName = "Kính Ray-Ban Wayfarer",
                            Style = "Vuông"
                        },
                        new
                        {
                            ProductID = 3,
                            BrandID = 2,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kính bản to sang trọng, họa tiết đặc trưng Gucci.",
                            IsActive = true,
                            Material = "Nhựa Acetate",
                            ProductName = "Kính Gucci Oversized GG0022",
                            Style = "Oversized"
                        },
                        new
                        {
                            ProductID = 4,
                            BrandID = 3,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kính thể thao năng động, chống trầy xước.",
                            IsActive = true,
                            Material = "Nhựa O-Matter",
                            ProductName = "Kính Oakley Holbrook",
                            Style = "Vuông"
                        },
                        new
                        {
                            ProductID = 5,
                            BrandID = 4,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kính mắt mèo nữ tính, tôn dáng khuôn mặt.",
                            IsActive = true,
                            Material = "Kim loại",
                            ProductName = "Kính Molsion Cat Eye MS3005",
                            Style = "Mắt mèo"
                        },
                        new
                        {
                            ProductID = 6,
                            BrandID = 4,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kính tròn phong cách retro, nhẹ và bền.",
                            IsActive = true,
                            Material = "Titanium",
                            ProductName = "Kính Molsion Round MS5012",
                            Style = "Tròn"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("VariantID");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/rayban-aviator-den.jpg",
                            IsMain = true,
                            VariantID = 1
                        },
                        new
                        {
                            ImageID = 2,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/rayban-aviator-gold.jpg",
                            IsMain = true,
                            VariantID = 2
                        },
                        new
                        {
                            ImageID = 3,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/rayban-wayfarer-den.jpg",
                            IsMain = true,
                            VariantID = 3
                        },
                        new
                        {
                            ImageID = 4,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/rayban-wayfarer-nau.jpg",
                            IsMain = true,
                            VariantID = 4
                        },
                        new
                        {
                            ImageID = 5,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/gucci-oversized-den.jpg",
                            IsMain = true,
                            VariantID = 5
                        },
                        new
                        {
                            ImageID = 6,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/gucci-oversized-nau.jpg",
                            IsMain = true,
                            VariantID = 6
                        },
                        new
                        {
                            ImageID = 7,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/oakley-holbrook-den.jpg",
                            IsMain = true,
                            VariantID = 7
                        },
                        new
                        {
                            ImageID = 8,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/oakley-holbrook-xanh.jpg",
                            IsMain = true,
                            VariantID = 8
                        },
                        new
                        {
                            ImageID = 9,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/molsion-cateye-hong.jpg",
                            IsMain = true,
                            VariantID = 9
                        },
                        new
                        {
                            ImageID = 10,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/molsion-cateye-bac.jpg",
                            IsMain = true,
                            VariantID = 10
                        },
                        new
                        {
                            ImageID = 11,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/molsion-round-bac.jpg",
                            IsMain = true,
                            VariantID = 11
                        },
                        new
                        {
                            ImageID = 12,
                            DisplayOrder = 1,
                            ImageUrl = "/images/products/molsion-round-gold.jpg",
                            IsMain = true,
                            VariantID = 12
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.ProductVariant", b =>
                {
                    b.Property<int>("VariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("VariantID");

                    b.HasIndex("ProductID", "Color")
                        .IsUnique();

                    b.ToTable("ProductVariants", t =>
                        {
                            t.HasCheckConstraint("CK_Variant_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_Variant_Stock", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            VariantID = 1,
                            Color = "Đen",
                            IsActive = true,
                            Price = 2500000m,
                            ProductID = 1,
                            StockQuantity = 20
                        },
                        new
                        {
                            VariantID = 2,
                            Color = "Vàng Gold",
                            IsActive = true,
                            Price = 2800000m,
                            ProductID = 1,
                            StockQuantity = 15
                        },
                        new
                        {
                            VariantID = 3,
                            Color = "Đen",
                            IsActive = true,
                            Price = 2200000m,
                            ProductID = 2,
                            StockQuantity = 25
                        },
                        new
                        {
                            VariantID = 4,
                            Color = "Nâu",
                            IsActive = true,
                            Price = 2200000m,
                            ProductID = 2,
                            StockQuantity = 10
                        },
                        new
                        {
                            VariantID = 5,
                            Color = "Đen",
                            IsActive = true,
                            Price = 7500000m,
                            ProductID = 3,
                            StockQuantity = 8
                        },
                        new
                        {
                            VariantID = 6,
                            Color = "Nâu",
                            IsActive = true,
                            Price = 7800000m,
                            ProductID = 3,
                            StockQuantity = 5
                        },
                        new
                        {
                            VariantID = 7,
                            Color = "Đen",
                            IsActive = true,
                            Price = 3200000m,
                            ProductID = 4,
                            StockQuantity = 18
                        },
                        new
                        {
                            VariantID = 8,
                            Color = "Xanh",
                            IsActive = true,
                            Price = 3400000m,
                            ProductID = 4,
                            StockQuantity = 12
                        },
                        new
                        {
                            VariantID = 9,
                            Color = "Hồng",
                            IsActive = true,
                            Price = 1800000m,
                            ProductID = 5,
                            StockQuantity = 30
                        },
                        new
                        {
                            VariantID = 10,
                            Color = "Bạc",
                            IsActive = true,
                            Price = 1750000m,
                            ProductID = 5,
                            StockQuantity = 22
                        },
                        new
                        {
                            VariantID = 11,
                            Color = "Bạc",
                            IsActive = true,
                            Price = 2100000m,
                            ProductID = 6,
                            StockQuantity = 16
                        },
                        new
                        {
                            VariantID = 12,
                            Color = "Vàng Gold",
                            IsActive = true,
                            Price = 2300000m,
                            ProductID = 6,
                            StockQuantity = 9
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("StaffID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            AccountID = 1,
                            Address = "Hà Nội",
                            Email = "admin@glassesshop.vn",
                            FullName = "Quản Trị Viên",
                            NumberPhone = "0901234567"
                        },
                        new
                        {
                            StaffID = 2,
                            AccountID = 2,
                            Address = "Hà Nội",
                            Email = "staff01@glassesshop.vn",
                            FullName = "Nguyễn Văn Bán",
                            NumberPhone = "0912345678"
                        });
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Cart", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("GlassesShop.Models.Entities.Cart", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.CartDetail", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlassesShop.Models.Entities.ProductVariant", "Variant")
                        .WithMany("CartDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Customer", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("GlassesShop.Models.Entities.Customer", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Order", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlassesShop.Models.Entities.Staff", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlassesShop.Models.Entities.ProductVariant", "Variant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Payment", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("GlassesShop.Models.Entities.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Product", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlassesShop.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.ProductVariant", "Variant")
                        .WithMany("Images")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.ProductVariant", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Staff", b =>
                {
                    b.HasOne("GlassesShop.Models.Entities.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("GlassesShop.Models.Entities.Staff", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Account", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.ProductVariant", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("GlassesShop.Models.Entities.Staff", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
